export enum Genre {
  ACTION_AND_ADVENTURE = "ACTION_AND_ADVENTURE",
  ANIMATION = "ANIMATION",
  COMEDY = "COMEDY",
  DOCUMENTARY = "DOCUMENTARY",
  DRAMA = "DRAMA",
  FANTASY = "FANTASY",
  HISTORICAL = "HISTORICAL",
  HORROR = "HORROR",
  NOIR = "NOIR",
  SCI_FI = "SCI_FI",
  WESTERN = "WESTERN",
}
