"""empty message

Revision ID: 5c4cfcaa6d00
Revises: e5364adb5ede
Create Date: 2025-06-12 21:17:35.310711

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c4cfcaa6d00"
down_revision = "e5364adb5ede"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("actors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("photo_url", sa.String(), nullable=True))

    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("poster_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_column("poster_url")

    with op.batch_alter_table("actors", schema=None) as batch_op:
        batch_op.drop_column("photo_url")

    # ### end Alembic commands ###
